"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, Github, Linkedin, Mail, MapPin, Phone, Download, ExternalLink } from "lucide-react";

const skills=["Python","C#","JavaScript","Power Apps","Power BI","SQL Server","HTML/CSS","Flask","D365 F&O","X++","SSRS Report"];
const experience=[
 {company:"Mazik Global",role:"D365 F&O Developer",date:"Dec 2025 – Present",items:["Designed and customized tables and forms, including defining relationships, using custom EDTs, adding data sources, and enabling CRUD operations with extensions of OTB tables.","Applied X++ basics to write runnable classes for insert, update, and delete operations.","Used and customized Data Entities for import/export.","Implemented batch jobs for automated Free Text Invoice generation.","Worked with SSRS reports, customizing both OTB and Custom reports.","Created menu items and menus, integrated them into modules.","Performed unit testing and functional testing of developed X++ customizations, Forms, Tables, and SSRS Reports before deployment.","Tested developed features against business requirements and fixed identified issues before moving changes to UAT."]},
 {company:"CubePeaks Technology",role:"Power Platform Developer",date:"Jul 2025 – Nov 2025",items:["Developed and maintained Power BI reports and dashboards to visualize key business metrics and support data-driven decisions.","Integrated and transformed data from multiple sources using Power Query and DAX for creating dynamic visuals.","Worked on invoice capture in Dynamics 365 F&O including matching, transferring, and voiding invoices to ensure accurate financial processing.","Assigned and managed security roles for users in Dynamics 365 F&O, including migrating roles from UAT/Sandbox to Production and configuring duties, privileges, sub-roles, and table permissions.","Created flows in Power Automate and used the Power Automate visual in Power BI to improve reporting and automation.","Worked on D365 F&O Forms, Tables, SSRS Reports, and X++ customizations.","Performed unit testing and functional testing of developed F&O customizations and fixed identified issues before UAT."]},
 {company:"Arch Technologies",role:"Machine Learning Intern",date:"Apr 2025 – Jun 2025",items:["Using Flask framework built a web application where users can input data and receive real-time predictions from a machine learning model trained on a CSV dataset.","Utilized Python libraries including NumPy, Pandas, and Scikit-learn for data cleaning, analysis, and building a predictive model.","Visualized a dataset using Seaborn & Matplotlib — created detailed statistical plots including bar charts, heatmaps, and histograms to explore trends, correlations, and data distribution."]},
 {company:"FastPace Dynamics",role:"Software Engineer – Intern",date:"Oct 2024 – Dec 2024",items:["Performed SQL querying to extract, manipulate and analyze data from different databases, optimizing performance and ensuring accurate reports.","Worked with Power BI to create interactive dashboards and reports for various projects, transforming raw data into meaningful insights.","Developed DAX functions and custom measures to enhance data analysis and provide dynamic, real-time reporting solutions.","Worked on D365 F&O development using X++, including Forms, Tables, and Reports.","Assisted with F&O customizations, unit testing, and functional testing before UAT."]},
 {company:"Mazik Global",role:"Power Platform – Intern",date:"Jul 2024 – Aug 2024",items:["Designed and developed a Customer Feedback Management System using ERD, Dataverse, Canvas App, and Model-Driven App.","Automated workflow with Power Automate to streamline feedback processing.","Completed Microsoft Learn modules for Power Apps."]},
 {company:"Inferifi LLC",role:"Dynamics 365 CRM & Power Platform – Intern",date:"Jul 2022 – Sept 2022",items:["Worked with MS SQL Server, C#, and JavaScript to perform CRM and development tasks.","Created calculator and stopwatch using JavaScript.","Built database tables and executed operations like joins, create, update, and insert."]}
];
const projects=[
 {title:"FYP — Health Care Model",desc:"A fully functional system which provides services in a hospital such as appointment scheduling, doctor availability, lab prescription, actor permissions and roles, and other services including surgery, radiology, and pathology."},
 {title:"Flask ShopCart",desc:"A full-stack ecommerce website built with Flask, Tailwind CSS, and MySQL, featuring an admin panel and a customer portal.",url:"https://github.com/Okasha00/Flask-ShopCart",images:["/projects/adminView.jpg","/projects/customerCart.jpg","/projects/CustomerView.jpg","/projects/login.jpg","/projects/ProductsList.jpg"]},
 {title:"Shoes Store",desc:"A responsive footwear ecommerce interface built with React, featuring a polished home page, product listings, product details, and an about page.",url:"https://glowingshoe.netlify.app/"}
];
const blogs=[
 {title:"Building a Custom Vendor List Form in Microsoft Dynamics 365 F&O",desc:"A practical guide to building a custom Vendor List Form with X++, Simple List patterns, table extensions, and vendor data sources.",url:"https://medium.com/@okashasameer0/building-a-custom-vendor-list-form-in-microsoft-dynamics-365-finance-operations-d365-f-o-baf6c7d0055e"},
 {title:"Building a Custom Inventory Report in D365FO",desc:"A custom SSRS report with item number filtering that brings inventory, on-hand, warehouse, and replenishment details into one view.",url:"https://medium.com/@okashasameer0/building-a-custom-inventory-report-in-d365fo-b2d97bc784a2"},
 {title:"Improving SSRS Report Design for Better Readability",desc:"A D365 Finance & Operations SSRS report enhanced with a Data Provider, temporary table, Auto Design, and alternating rows for a clearer layout.",url:"https://medium.com/@okashasameer0/improving-ssrs-report-design-for-better-readability-e018873e3db1"}
];
const certs=["Artificial Intelligence — PIAIC | March 2023","Microsoft Dynamics Training CRM — KAISPE Academy | June 2024","Introduction to Power BI — DataCamp | February 2025"];

export default function Home(){
 const [typedTitle, setTypedTitle] = useState("");
 const [selectedImage, setSelectedImage] = useState<string | null>(null);
 useEffect(() => {
  const title = "I'm a Software Engineer with experience working with Microsoft Dynamics 365 Finance & Operations (D365 F&O), Power Platform, Web Development, Full-Stack Developer.";
  let position = 0;
  const timer = window.setInterval(() => {
   setTypedTitle(title.slice(0, position + 1));
   position += 1;
   if (position === title.length) window.clearInterval(timer);
  }, 55);
  return () => window.clearInterval(timer);
 }, []);
 return <main>
    <nav className="fixed top-0 z-50 w-full border-b border-[#29443b]/80 bg-[#0b1715]/80 backdrop-blur-xl"><div className="container flex h-16 items-center justify-between"><a href="#home" className="font-bold tracking-wide">OS<span className="text-[#f27d5b]">.</span></a><div className="hidden gap-6 text-sm text-[#aabbb0] md:flex">{["About","Skills","Experience","Projects","Blog","Contact"].map(x=><a key={x} href={x === "About" ? "#home" : '#'+x.toLowerCase()} className="transition-colors hover:text-[#9ee7c2]">{x}</a>)}</div></div></nav>
    <section id="home" className="grid-bg min-h-[78vh] pt-32"><div className="container flex min-h-[68vh] flex-col justify-center"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="max-w-4xl"><h1 className="text-5xl font-black leading-tight md:text-7xl">Okasha Sameer<span className="text-[#f27d5b]">.</span></h1><h2 className="typewriter-title mt-5 text-2xl font-semibold leading-relaxed text-[#d6e2d9] md:text-3xl">{typedTitle}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-[#aabbb0]">A Software Engineering graduate with hands-on experience in Dynamics 365 CRM, D365 Finance &amp; Operations, Power Platform, Power BI, and database technologies including MS SQL Server and MySQL. Skilled in X++, C#, JavaScript, Python, HTML, and CSS, with practical experience in D365 F&amp;O customizations, Power BI reporting and data visualization, ASP.NET Core MVC, Flask, and database development using SQL Server and MySQL. Experienced in SQL querying, database design, data management, and developing scalable, secure, and efficient business and web applications tailored to business requirements.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#experience" className="rounded-full bg-[#f27d5b] px-6 py-3 font-semibold text-[#0b1715] transition-transform hover:-translate-y-1 hover:bg-[#ff9675]">View Experience <ArrowUpRight className="ml-1 inline" size={17}/></a><a href="mailto:okashasameer00@gmail.com" className="rounded-full border border-[#9ee7c2]/30 px-6 py-3 font-semibold transition-colors hover:border-[#9ee7c2] hover:bg-[#9ee7c2]/10">Contact Me</a></div></motion.div><div className="mt-12 flex flex-wrap gap-5 text-sm text-[#aabbb0]"><span><MapPin className="mr-2 inline" size={16}/>Karachi, Pakistan</span><span><Phone className="mr-2 inline" size={16}/>+92-340-4795529</span><a href="mailto:okashasameer00@gmail.com" className="transition-colors hover:text-[#9ee7c2]"><Mail className="mr-2 inline" size={16}/>okashasameer00@gmail.com</a></div></div></section>

    <section id="skills" className="container py-24"><SectionTitle eyebrow="" title="CORE COMPETENCIES"/><motion.div initial="hidden" whileInView="visible" viewport={{once:true,amount:.2}} variants={{visible:{transition:{staggerChildren:.06}}}} className="flex flex-wrap gap-3">{skills.map(s=><motion.span variants={{hidden:{opacity:0,y:12},visible:{opacity:1,y:0}}} key={s} className="rounded-full border border-[#29443b] bg-[#11231f] px-5 py-3 text-[#d6e2d9] transition hover:-translate-y-1 hover:border-[#f27d5b]/70 hover:text-[#f27d5b]">{s}</motion.span>)}</motion.div></section>

    <section id="experience" className="border-y border-[#29443b]/70 bg-[#11231f]/45 py-24"><div className="container"><SectionTitle eyebrow="" title="PROFESSIONAL EXPERIENCE"/><div className="space-y-12">{experience.map((e,i)=><motion.article key={i} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} transition={{delay:i*.06}} viewport={{once:true,amount:.15}} className="relative border-l border-[#f27d5b]/40 pl-7"><span className="timeline-dot absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full bg-[#f27d5b]"/><div className="flex flex-col justify-between gap-2 md:flex-row"><div><h3 className="text-xl font-bold">{e.role}</h3><p className="mt-1 text-[#9ee7c2]">{e.company}</p></div><span className="text-sm text-[#71877b]">{e.date}</span></div><ul className="mt-5 space-y-3 text-[#aabbb0]">{e.items.map((x,j)=><li key={j} className="leading-7">• {x}</li>)}</ul></motion.article>)}</div></div></section>

    <section id="projects" className="border-y border-[#29443b]/70 bg-[#11231f]/45 py-24"><div className="container"><SectionTitle eyebrow="" title="PROJECTS"/><div className="grid max-w-3xl gap-6 md:grid-cols-2">{projects.map(p=><motion.div whileHover={{y:-6}} transition={{type:"spring",stiffness:300}} key={p.title} className="rounded-3xl border border-[#29443b] bg-[#11231f] p-7"><div className="mb-6 flex items-start justify-between"><a href={p.url} target="_blank" rel="noreferrer" aria-label={`View ${p.title} on GitHub`} className="rounded-2xl bg-[#f27d5b]/10 p-3 text-[#f27d5b] transition-colors hover:bg-[#f27d5b]/20"><ExternalLink size={20}/></a></div><h3 className="text-xl font-bold">{p.title}</h3><p className="mt-4 leading-7 text-[#aabbb0]">{p.desc}</p>{p.images && <div className="mt-6 grid grid-cols-2 gap-2">{p.images.map(image=><button type="button" key={image} onClick={()=>setSelectedImage(image)} aria-label={`Enlarge ${p.title} screenshot`} className="cursor-zoom-in"><img src={image} alt={`${p.title} screenshot`} className="aspect-video w-full rounded-lg border border-[#25415f] object-cover transition-transform hover:scale-[1.03]"/></button>)}</div>}</motion.div>)}</div></div></section>

    {selectedImage && <div role="dialog" aria-modal="true" aria-label="Enlarged project screenshot" className="fixed inset-0 z-[70] flex items-center justify-center bg-[#020817]/90 p-5 backdrop-blur-sm" onClick={()=>setSelectedImage(null)}><button type="button" aria-label="Close enlarged screenshot" className="absolute right-5 top-5 rounded-full border border-[#7dd3fc]/40 px-4 py-2 text-2xl text-[#f4f7fb] hover:border-[#7dd3fc]">×</button><img src={selectedImage} alt="Enlarged project screenshot" className="max-h-[90vh] max-w-[94vw] rounded-xl object-contain shadow-2xl" onClick={event=>event.stopPropagation()}/></div>}

    <section id="blog" className="container py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionTitle eyebrow="" title="D365 F&O Blogs"/><a href="https://medium.com/@okashasameer0" target="_blank" rel="noreferrer" className="mb-12 font-semibold text-[#7dd3fc] transition-colors hover:text-white">View Medium profile <ArrowUpRight className="ml-1 inline" size={17}/></a></div><div className="grid gap-6 md:grid-cols-3">{blogs.map(blog=><motion.article whileHover={{y:-6}} transition={{type:"spring",stiffness:300}} key={blog.url} className="rounded-3xl border border-[#25415f] bg-[#101e31] p-7"><div className="mb-6 flex items-start justify-between"><div className="rounded-2xl bg-[#4ea8ff]/10 p-3 text-[#7dd3fc]"><ExternalLink size={20}/></div><span className="text-xs font-semibold uppercase tracking-[.18em] text-[#858477]">Medium</span></div><h3 className="text-xl font-bold">{blog.title}</h3><p className="mt-4 leading-7 text-[#aebdce]">{blog.desc}</p><a href={blog.url} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center font-semibold text-[#4ea8ff] transition-colors hover:text-[#7dd3fc]">Read article <ArrowUpRight className="ml-1" size={17}/></a></motion.article>)}</div></section>

    <section className="container grid gap-16 py-24 md:grid-cols-2"><div><SectionTitle eyebrow="" title="EDUCATION"/><div className="space-y-7"><Info title="Bachelors in Software Engineering" sub="Usman Institute of Technology" meta="2019 – 2023"/><Info title="Pre-Engineering" sub="Govt. Delhi College" meta="2016 – 2018"/><Info title="Computer Science" sub="Usman Public School" meta="2016"/></div></div><div><SectionTitle eyebrow="" title="CERTIFICATIONS"/><div className="space-y-4">{certs.map(c=><motion.div whileHover={{x:5}} key={c} className="rounded-2xl border border-[#29443b] bg-[#11231f] p-5 text-[#d6e2d9]">{c}</motion.div>)}</div></div></section>

  <section id="contact" className="border-t border-[#29443b]/70 py-24"><div className="container text-center"><SectionTitle eyebrow="Contact" title="Let's Connect"/><p className="mx-auto max-w-xl text-[#aabbb0]">Interested in opportunities involving D365 F&O, Power Platform, data, or software development? Get in touch.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><a href="mailto:okashasameer00@gmail.com" className="rounded-full bg-[#f27d5b] px-6 py-3 font-semibold text-[#0b1715] transition-transform hover:-translate-y-1 hover:bg-[#ff9675]"><Mail className="mr-2 inline" size={17}/>Email</a><a href="https://github.com/Okasha00" target="_blank" rel="noreferrer" className="rounded-full border border-[#29443b] px-6 py-3 transition-colors hover:border-[#9ee7c2] hover:text-[#9ee7c2]"><Github className="mr-2 inline" size={17}/>GitHub</a><a href="https://www.linkedin.com/in/okasha-sameer-774b561b0" target="_blank" rel="noreferrer" className="rounded-full border border-[#29443b] px-6 py-3 transition-colors hover:border-[#9ee7c2] hover:text-[#9ee7c2]"><Linkedin className="mr-2 inline" size={17}/>LinkedIn</a></div></div></section>
  <footer className="border-t border-[#29443b]/70 py-8 text-center text-sm text-[#71877b]">© {new Date().getFullYear()} Okasha Sameer. All rights reserved.</footer>
 </main>
}
function SectionTitle({eyebrow,title}:{eyebrow:string,title:string}){return <motion.div initial={{opacity:0,x:-18}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.35}} transition={{duration:.5}} className="mb-12">{eyebrow && <p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#f27d5b]">{eyebrow}</p>}<h2 className="text-4xl font-black md:text-5xl">{title}</h2></motion.div>}
function Info({title,sub,meta}:{title:string,sub:string,meta:string}){return <motion.div initial={{opacity:0,x:-12}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.5}} transition={{duration:.45}} className="border-l border-[#29443b] pl-5"><h3 className="font-bold">{title}</h3><p className="mt-1 text-[#9ee7c2]">{sub}</p><p className="mt-1 text-sm text-[#71877b]">{meta}</p></motion.div>}
